[providers]
nodejs = "nodejs"

[phases.setup]
nixPkgs = ["python3", "python3.pkgs.pip"]

[phases.install]
cmds = [
  "npm install",
  "pip3 install --break-system-packages -r requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"